# Generated by Django 6.1 on 2026-08-12 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('period', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('template_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'unique_together': {('project_id', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('WTT', 'Working Time Table'), ('PPRP', 'Perubahan Perencanaan'), ('GHP', 'Ground Handling Performance'), ('TEMPLATE', 'Template Output')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('parser_version', models.CharField(default='1.0', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_files',
                'unique_together': {('project', 'file_type', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('flight_number', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('flight_date', models.DateField()),
                ('aircraft', models.CharField(blank=True, max_length=20)),
                ('std', models.TimeField(blank=True, null=True)),
                ('sta', models.TimeField(blank=True, null=True)),
                ('atd', models.TimeField(blank=True, null=True)),
                ('ata', models.TimeField(blank=True, null=True)),
                ('pprp_letter', models.CharField(blank=True, max_length=100)),
                ('pprp_date', models.DateField(blank=True, null=True)),
                ('operational_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scheduleversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.project')),
                ('source_pprp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pprp_schedules', to='core.sourcefile')),
                ('source_wtt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wtt_schedules', to='core.sourcefile')),
            ],
            options={
                'db_table': 'schedule_versions',
                'indexes': [models.Index(fields=['project', 'flight_number', 'flight_date'], name='schedule_ve_project_6f9eec_idx'), models.Index(fields=['flight_number', 'flight_date', 'origin', 'destination'], name='schedule_ve_flight__c6801f_idx'), models.Index(fields=['project', 'is_active'], name='schedule_ve_project_235264_idx')],
            },
        ),
    ]
