# Generated by Django 6.1 on 2026-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='file_type',
            field=models.CharField(choices=[('WTT', 'Working Time Table'), ('PPRP', 'Perubahan Perencanaan'), ('GHP', 'Ground Handling Performance')], max_length=10),
        ),
    ]
