# Generated by Django 6.1 on 2026-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sourcefile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='delay_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
