# Generated by Django 6.1 on 2026-09-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduleversion_delay_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='ghp_atd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='ghp_std',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
