# Generated by Django 6.1 on 2026-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduleversion_ghp_atd_scheduleversion_ghp_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleversion',
            name='delay_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
