"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1=ap1o$cndz-8p=0h9$s!ugn86t^n#8&zyfj&wso5bx+v510sd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'cilink_report'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'  # WIB (UTC+7)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'

from django.urls import reverse_lazy

UNFOLD = {
    "STYLES": [
        lambda request: "/static/css/unfold_override.css?v=7",
    ],
    "SITE_TITLE": "CITILINK AVIOR",
    "SITE_HEADER": "CITILINK AVIOR",
    "SITE_SUBHEADER": "AViation Operations Report",
    # Aplikasi ini tidak punya situs publik di luar admin: "/" hanya redirect
    # ke /admin/, sehingga tombol "Return to site" di halaman login berputar
    # kembali ke halaman login. None menyembunyikannya (unfold/helpers/
    # unauthenticated_header.html membungkusnya dengan {% if site_url %}).
    "SITE_URL": None,
    "COLORS": {
        # Satu tangga warna yang diturunkan dari hijau Citilink (#006b32 = 600).
        # Sebelumnya 50-500 dan 700-900 memakai hijau Tailwind sehingga 700
        # lebih terang daripada 600; kelas primary-* jadi tidak bisa dipercaya
        # dan template terpaksa menulis #006b32 secara manual.
        "primary": {
            "50": "#f0f8f3",
            "100": "#dcefe3",
            "200": "#b8dfc7",
            "300": "#86c8a3",
            "400": "#4faa79",
            "500": "#1f8a55",
            "600": "#006b32",  # Citilink primary green
            "700": "#005a2a",
            "800": "#004a23",
            "900": "#003b1c",
            "950": "#002310",
        },
        # Unfold membangkitkan --color-<nama>-<bobot> dari setiap kunci di sini
        # (lihat unfold/layouts/skeleton.html), jadi bobot tambahan boleh
        # didaftarkan. "350" adalah titik tengah base-300 (oklch 87.2%) dan
        # base-400 (oklch 70.7%), dipakai untuk border input di halaman login:
        # 300 terlalu tipis, 400 terlalu tegas. Bobot base lain tetap bawaan
        # Unfold karena deep-merge hanya menimpa kunci yang disebut.
        "base": {
            "350": "oklch(79% .016 259.8)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Navigasi",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Upload Data",
                        "icon": "cloud_upload",
                        "link": reverse_lazy("custom_upload"),
                    },
                    {
                        "title": "Jadwal Penerbangan",
                        "icon": "flight_takeoff",
                        "link": reverse_lazy("admin:core_scheduleversion_changelist"),
                    },
                    {
                        "title": "Project",
                        "icon": "folder",
                        "link": reverse_lazy("admin:core_project_changelist"),
                    },
                ],
            },
            {
                "title": "Administrasi",
                "separator": True,
                "items": [
                    {
                        "title": "Pengguna",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Grup",
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
